@apiURL =  {{$dotenv PRODUCTS_API}}
@aiURL = {{$dotenv AI_API}}

### Get alla prodkter

GET {{apiURL}}

### GET en produkt

GET {{apiURL}}/1001

### POST skapa en produkt

POST {{aiURL}}
Content-Type: application/json
{
    "question": "Fungerar detta",
}

### PUT upppdatera en produkt

PUT  {{apiURL}}/1002
Content-Type: application/json
{
    "name": "Fedora",
    "price": 50
}

### PATCH uppdatera ett enskilt fält i en produkt
PATCH {{apiURL}}/1001
Content-Type: application/json
{
    "price": 79.99
}

### DELETE ta bort en produkt

DELETE {{apiURL}}/1004